services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - type: volume
        source: nas
        target: /media
    restart: 'unless-stopped'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  jellyfin-config:
    external: true
  jellyfin-cache:
    external: true
  nas:
    driver_opts:
      type: "nfs"
      o: "nfsvers=3,addr=192.168.1.83,rw"
      device: ":/volume1/Media/collections"
